services:
    odiseo_notification.builder.notification:
        class: Odiseo\Bundle\NotificationBundle\Builder\NotificationBuilder
        arguments: [ '@odiseo_notification.repository.notification', '@odiseo_notification.manager.notification', '@security.token_storage' ]
